"""Constants for the MitTog integration."""

from datetime import timedelta

DOMAIN = "mittog"

# Frontend card shipped with the integration.
VERSION = "0.2.0"
CARD_URL = "/mittog_static/mittog-card.js"

WS_URL = "wss://api.mittog.dk/api/ws/departure/{station}/dinstation/"
WS_ORIGIN = "https://mittog.dk"

# The server pushes a full board every ~5 s. If nothing arrives for this long
# the connection is considered dead and is re-established.
WS_IDLE_TIMEOUT = timedelta(seconds=60)
WS_RECONNECT_MIN = 5
WS_RECONNECT_MAX = 120

CONF_STATION = "station"
CONF_STATION_NAME = "station_name"
CONF_TIME = "time"
CONF_DIRECTION = "direction"

SUBENTRY_DEPARTURE = "departure"

DIRECTION_UP = "UP"
DIRECTION_DOWN = "DOWN"
DIRECTIONS = [DIRECTION_UP, DIRECTION_DOWN]

# A train counts as delayed from this many minutes (DSB's own threshold is 3).
DELAY_THRESHOLD_MIN = 3

# Keep showing a departed train for this long before looking for the next one.
DEPARTED_GRACE = timedelta(minutes=60)

# Banedanmark station codes seen in the feed. Only used for display.
# Station names as mittog.dk itself shows them (extracted from the site's
# station list). The feed also uses a few technical codes that the site maps
# onto public stations before display; see STATION_ALIASES.
STATION_NAMES: dict[str, str] = {
    "AB": "Aalborg",
    "ABL": "Aalborg Lufthavn",
    "ABV": "Aalborg Vestby",
    "AD": "Arden",
    "AK": "Alken",
    "AP": "Aarup",
    "AR": "Aarhus H",
    "BAH": "Baunhøj",
    "BB": "Brande",
    "BD": "Bred",
    "BET": "Brejning",
    "BG": "Bording",
    "BIC": "Birk Centerpark",
    "BIM": "Billum",
    "BJ": "Bjerringbro",
    "BK": "Børkop",
    "BL": "Brønderslev",
    "BM": "Bramming",
    "BN": "Bedsted Thy",
    "BO": "Borup",
    "BOT": "Boulevarden",
    "BP": "Brørup",
    "BRR": "Brøns",
    "BS": "Borris",
    "BU": "Bur",
    "BUK": "Bunken",
    "BW": "Bredebro",
    "CPH": "CPH Lufthavn",
    "DS": "Døstrup Sønderjylland",
    "DY": "Dyreby",
    "EB": "Ejby",
    "EK": "Eskilstrup",
    "EMM": "Emmersbæk",
    "ES": "Esbjerg",
    "ESN": "Spangsbjerg",
    "EV": "Engesvang",
    "FA": "Fredericia",
    "FH": "Frederikshavn",
    "FHV": "Frederikshavnsvej",
    "FRS": "Fruens Bøge",
    "FRT": "Frisvadvej",
    "GD": "Gelsted",
    "GJE": "Gjesing",
    "GP": "Gødstrup",
    "GS": "Gredstedbro",
    "GST": "Gråsten",
    "GT": "Gadstrup",
    "GU": "Guldager",
    "GW": "Give",
    "GZ": "Glumsø",
    "GÅ": "Gårde",
    "GÆ": "Espergærde",
    "GØ": "Gørding",
    "HA": "Hadsten",
    "HB": "Hobro",
    "HD": "Havdrup",
    "HE": "Hee",
    "HED": "Hedensted",
    "HF": "Herfølge",
    "HG": "Helsingør",
    "HGP": "Herregårdsparken",
    "HH": "Hedehusene",
    "HHS": "Hirtshals",
    "HJ": "Hjørring",
    "HJS": "Hjallese",
    "HJØ": "Hjørring Øst",
    "HK": "Holbæk",
    "HL": "Hellerup",
    "HM": "Hjerm",
    "HN": "Hinnerup",
    "HNN": "Henne",
    "HO": "Holstebro",
    "HON": "Horne",
    "HP": "Holmstrup",
    "HQ": "Holsted",
    "HR": "Herning",
    "HRM": "Herning Messecenter",
    "HS": "Horsens",
    "HTÅ": "Høje Taastrup",
    "HU": "Hammerum",
    "HUL": "Hulsig",
    "HUM": "Humlebæk",
    "HV": "Hvalsø",
    "HW": "Hvidbjerg",
    "HX": "Hørning",
    "HYV": "Hyllerslev",
    "HZ": "Haslev",
    "HÆ": "Hørdum",
    "HØ": "Højslev",
    "HØS": "Højby (Fyn)",
    "ID": "Vildbjerg",
    "IK": "Ikast",
    "IS": "Sig",
    "JAD": "Janderup",
    "JEG": "Jegum",
    "JEU": "Jerup",
    "JL": "Jelling",
    "JNE": "Jerne",
    "JY": "Jyderup",
    "KA": "Kauslunde",
    "KB": "Kalundborg",
    "KBØ": "Kalundborg Øst",
    "KD": "Kolding",
    "KH": "København H",
    "KJ": "Køge",
    "KJN": "Køge Nord",
    "KK": "Østerport",
    "KL": "Klampenborg",
    "KN": "Nørreport",
    "KS": "Knabstrup",
    "KT": "Kvægtorvet",
    "KV": "Kvissel",
    "KVS": "Kværndrup",
    "KW": "Kliplev",
    "KÆ": "Kibæk",
    "KØ": "Korsør",
    "LA": "Laven",
    "LG": "Langå",
    "LHE": "Lilleheden",
    "LIH": "Lindholm",
    "LJ": "Lejre",
    "LK": "Lunderskov",
    "LM": "Lem",
    "LN": "Lyngs",
    "LU": "Lundby",
    "LUJ": "Lunde",
    "LV": "Langeskov",
    "LW": "Lille Skensved",
    "LØT": "Løftgård",
    "MD": "Middelfart",
    "MØ": "Mørkøv",
    "NA": "Nørre Aaby",
    "NAP": "Napstjert",
    "NBL": "Nørre Nebel",
    "NEL": "København Syd",
    "NF": "Nykøbing F",
    "NG": "Nyborg",
    "NI": "Nivå",
    "NO": "Oddesund Nord",
    "NV": "Nørre Alslev",
    "NÆ": "Næstved",
    "NÆN": "Næstved Nord",
    "OD": "Odense",
    "OG": "Skalborg",
    "OH": "Orehoved",
    "OJ": "Vojens",
    "OK": "Kokkedal",
    "OKS": "Oksbøl",
    "OL": "Holme-Olstrup",
    "OSS": "Odense Sygehus",
    "OVT": "Outrup",
    "PA": "Padborg",
    "PDS": "Pederstrup",
    "PE": "Vipperød",
    "RB": "Ribe",
    "RBN": "Ribe Nørremark",
    "RD": "Randers",
    "RE": "Ringe",
    "REJ": "Rejsby",
    "RF": "Rødby Færge",
    "RG": "Ringsted",
    "RI": "Sjørring",
    "RIM": "Rimmen",
    "RJ": "Ringkøbing",
    "RK": "Rødkærsbro",
    "RO": "Roskilde",
    "ROF": "Roskilde Festivalplads",
    "RQ": "Rødekro",
    "RT": "Regstrup",
    "RU": "Rungsted Kyst",
    "RUS": "Rudme",
    "RY": "Ry",
    "SA": "Sindal",
    "SC": "Skalbjerg",
    "SD": "Skanderborg",
    "SDB": "Sønderborg",
    "SE": "Svebølle",
    "SEJ": "Sejstrup",
    "SG": "Slagelse",
    "SGB": "Skagen",
    "SIS": "Stenstrup Syd",
    "SJ": "Skjern",
    "SK": "Skive",
    "SL": "Silkeborg",
    "SM": "Stoholm",
    "SN": "Svenstrup J",
    "SNE": "Snedsted",
    "SO": "Sorø",
    "SP": "Sparkær",
    "SQ": "Snekkersten",
    "SR": "Støvring",
    "STB": "Strandby",
    "STR": "Struer",
    "STS": "Stenstrup",
    "STU": "Studsgård",
    "SV": "Svejbæk",
    "SVG": "Svendborg",
    "SVV": "Svendborg Vest",
    "SÅ": "Skodsborg",
    "SØ": "Skørping",
    "TA": "Tarm",
    "TB": "Tjæreborg",
    "TD": "Troldhede",
    "TDR": "Tønder",
    "TE": "Tinglev",
    "TGV": "Teglgårdsvej",
    "TH": "Tureby",
    "TI": "Thisted",
    "TL": "Taulov",
    "TM": "Tim",
    "TNB": "Tornby",
    "TO": "Tolne",
    "TP": "Tommerup",
    "TR": "Tistrup",
    "TRK": "Trekroner",
    "TRN": "Tønder Nord",
    "TY": "Thyregod",
    "TÅT": "Tårnby",
    "TØ": "Tølløse",
    "UF": "Ulfborg",
    "UL": "Uglev",
    "UM": "Humlum",
    "UP": "Ulstrup",
    "UR": "Hurup Thy",
    "UU": "Aulum",
    "VA": "Varde",
    "VAL": "Valby",
    "VAV": "Varde Vest",
    "VB": "Vedbæk",
    "VD": "Hviding",
    "VEM": "Vemb",
    "VG": "Viborg",
    "VI": "Viby Jylland",
    "VID": "Vidstrup",
    "VIS": "Visby",
    "VJ": "Vejle",
    "VJS": "Vejle Sygehus",
    "VKA": "Varde kaserne",
    "VLH": "Vellingshøj",
    "VM": "Vamdrup",
    "VN": "Vejen",
    "VNO": "Varde Nord",
    "VO": "Vordingborg",
    "VP": "Vinderup",
    "VR": "Vrå",
    "VRØ": "Vrøgum",
    "VY": "Viby Sj",
    "YD": "Ydby",
    "ÅLB": "Ålbæk",
    "ÅS": "Årslev",
    "ÆK": "Skærbæk",
    "ØG": "Ølgod",
    "ØLB": "Ølby",
    "ØRE": "Ørestad",
}

# Technical codes the feed emits that mittog.dk rewrites before lookup:
# HGL is the Helgoland depot behind Østerport, HTAA an ASCII spelling.
STATION_ALIASES: dict[str, str] = {
    "HGL": "KK",
    "HTAA": "HTÅ",
}

# Rolling-stock codes from the feed's UnitType, for a friendlier label.
UNIT_TYPES: dict[str, str] = {
    "MFA": "IC3",
    "MFB": "IC3",
    "ER": "IR4",
    "MG": "IC4",
    "MQ": "Desiro",
    "MP": "IC2",
    "ET": "Øresundstog",
    "EB": "Lokomotiv",
    "ME": "Lokomotiv",
    "B": "Dobbeltdækker",
    "BK": "Dobbeltdækker",
    "ABS": "Dobbeltdækker",
}
